#!/usr/bin/env ruby
require "git_diff"

out = []
diff = GitDiff.from_string(`git diff --word-diff=porcelain --word-diff-regex='\\w+|[^\\s\\w]' HEAD`)
diff.files.each do |file|
  file.hunks.each do |hunk|
    del_buf = nil
    flush_del_buf = -> {
      if del_buf
        out << "Remove #{del_buf.content[1..-1].strip}"
        del_buf = nil
      end
    }
    hunk.lines.each do |line|
      text = line.content[1..-1].strip
      if line.content[0] == '+' && !text.empty?
        if del_buf
          out << "Switch #{del_buf.content[1..-1].strip} to #{text}"
          del_buf = nil
        else
          out << "Add #{text}"
        end
      elsif line.content[0] == '-' && !text.empty?
        flush_del_buf[]
        del_buf = line
      else
        flush_del_buf[]
      end
    end
    flush_del_buf[]
  end
end

raise "Cannot parse changes" if out.length == 0

prefix = ENV['AUTOCOMMIT_PREFIX'] || ''
commit_message = "#{prefix}#{prefix.empty? ? '' : ' '}#{out.uniq.join(', ')}"
puts commit_message
if !ARGV.include?('-f')
  puts
  puts "Enter to commit, Ctrl-C to cancel."
  $stdin.gets
end
system "git", "commit", "-a", "-m", commit_message or raise "Cannot commit"
